### ISSUE TITLE
SharpHound4 Execute Assembly Failed

### ISSUE THREAD

**Issue by skylerknecht** [skylerknecht/connect#1]
# Failed to Run Execute Assembly
- Agent: C#
- Command: Execute Assembly

Attempting to run SharpHound 4.0 failed with the following output:

```
Failed to execute assembly with argument(s): --group=all
System.IO.FileNotFoundException: Could not load file or assembly 'SharpHoundCommonLib, Version=2.0.13.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'SharpHoundCommonLib, Version=2.0.13.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Agent.Program.Invoke(Byte[] asmb_bytes, String[] asmb_args)
   at Agent.Program.ExecuteAssembly(String key, Byte[] asmb, String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

**Comment by Invoke-Mimikatz** [comment]
merge your sharphound dependencies in with ILMerge ;)
