### ISSUE TITLE
Thread synchronization with Socks

### ISSUE THREAD

**Issue by skylerknecht** [skylerknecht/connect#8]
This happens sometimes when I CTRL+C xfreerdp when I used it through the proxy

```
[*] Client VXzgiAYFdg stopped streaming
Exception in thread Thread-549:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/skyler/connect/connect/socks/manager.py", line 37, in handle_socks_task_results
    for socks_server in self.socks_servers.values():
RuntimeError: dictionary changed size during iteration
```

**Comment by skylerknecht** [comment]
Removed socks from connect
